# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'controlBtn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for controlBtn

    pod 'YYImage'

  target 'controlBtnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'controlBtnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
